version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        volumes:
            - myapp:/home/node/app    
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user
            #POSTGRES_DATABASE: db
            #DATABASE_URL: postgres://user:password@postgres:5432/db
            NODE_ENV: production
            PORT: 2000
        env_file: .env
        ports:
            - "2000:2000"
    postgres:
        image: postgres:10.4
        ports:
           - "35000:5432"
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: "remox"
        volumes: 
           - db-data:/var/lib/postgresql/data

volumes: 
  db-data:
  myapp:  